### PR TITLE
make SetExpire public, so that expiry date can be computed

### PR DESCRIPTION
**Pull request by krzyzacy**
Mostly working - need to set `expiryDate` so that we don't deprecate existing images

/assign @adjackura

### CODE REVIEW

**Comment by krzyzacy** [comment]
:man_facepalming: also... how would I undeprecate an image?

**Comment by krzyzacy** [comment]
nvm - `gcloud compute images deprecate` can actually undeprecate an image :joy:

**Comment by krzyzacy** [comment]
(merge? btw you can automate merge with prow :-p )

**Comment by adjackura** [comment]
Pft, forgot to merge, and yeah we are working on a much better design for all our github repos with full automated merges, auto releases and all that.

**Comment by krzyzacy** [comment]
(I'm also bring up a Google owned prow in https://github.com/GoogleCloudPlatform/oss-test-infra, in case you'd want to use a shared instance)

**Pull request merged**
