### PR TITLE
deprecate master branch

### PR DESCRIPTION
**Pull request by gaohannk**

### CODE REVIEW

**Review by zoran15 — COMMENTED** [review]
What is this change about? We use master as our main branch, build all the tools from it etc. We can't just delete it.

**Comment by gaohannk** [comment]
@zoran15  Hi Zoran: We propose a change which deprecate master branch and change to main. Here is the proposal. 
I am working on to make change in guest-agent and test the workflow. 
https://docs.google.com/document/d/1t1wQVseCPoi_4BTIT77RRS0AsygM0dIRtsOH_ZUjPwA/edit#

**Comment by gaohannk** [comment]
Here is the step to make this change. https://docs.google.com/document/d/1ekSMf6u2E9KZ8xOTsoQ7OjtJkZ5gZ-x73kXN0IGVwWY/edit#

**Pull request closed without merging**
