### PR TITLE
daisy: upload sources from IncludeWorkflow

### PR DESCRIPTION
**Pull request by helen-fornazier**
The uploadSources function uploads files from the SubWorkflow step but
IncludeWorkflow step was missing.

### CODE REVIEW

**Comment by adjackura** [comment]
We treat includeworklows differently, they are merged with their parent.

See https://github.com/GoogleCloudPlatform/compute-image-tools/blob/master/daisy/step_includeworkflow.go#L117

**Comment by helen-fornazier** [comment]
right, I thought that only the namespace would be shared and my tests where not working using IncludeWorkflow, but I can change it to subworkflow.
Sorry about the noise

**Comment by adjackura** [comment]
If you have workflows that you expect to pass and don't I can look into it, I know the subworkflow/includeworkflow sharing system is a bit complicated and we have had bugs in the past

**Comment by helen-fornazier** [comment]
@adjackura No need, I can use SubWorflow.
The workflow pass with SubWorkflow but it doesn't pass if I use IncludeWorkflow for two reasons:
1) It can't find the files to download (I didn't investigate if it should find it thought, I need to take a look)
2) I use the FULLNAME variable to deduct the name of the resources, but FULLNAME is constructed with the name of all parents, maybe it should behave differently when used with IncludeWorkflow (so it matches the suffix of the resources).

**Pull request closed without merging**
