### PR TITLE
Move accelerator_images up one level to work better with concourse

### PR DESCRIPTION
**Pull request by a-crate**
/assign @jjerger

### CODE REVIEW

**Comment by a-crate** [comment]
/hold
Sorry, found some bugs. One minute.

**Review by jjerger — COMMENTED** [review]
/lgtm

**Comment by a-crate** [comment]
/unhold
OK @jjerger should be ready

**Comment by jjerger** [comment]
Oops I had missed this prior to opening a PR to do this myself; we are safe to close this one

**Pull request closed without merging**
