### PR TITLE
Delete code for import/export tools

### PR DESCRIPTION
**Pull request by EricEdens**
We moved this code to the [compute-image-import](https://github.com/GoogleCloudPlatform/compute-image-import) repo. The following CLI tools remain:

 - diagnostics
 - gce_export
 - gce_image_publish
 - gce_windows_upgrade

In draft while we update Prow to remove the presubmits that are no longer applicable: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1587

### CODE REVIEW

**Comment by dntczdx** [comment]
why is gce_export not moved?

**Comment by EricEdens** [comment]
> why is gce_export not moved?

The team wanted to keep `gce_export` here since it's a strong dependency of building official images. `gce_vm_image_export` goes to the new repo, however, since it's the implementation behind `gcloud compute images export`.

**Comment by dntczdx** [comment]
Why is it closed?

**Comment by EricEdens** [comment]
I should have updated this thread -- I opened a new one, since Prow (for
some reason that I can't determine) was running the boot inspect tests,
even though I deleted them from the OSS test infra prow config.

I created a new PR here:
https://github.com/GoogleCloudPlatform/compute-image-tools/pull/1917

**Pull request closed without merging**
