### PR TITLE
Update Docker version to latest

### PR DESCRIPTION
**Pull request by rofuentes**
* See the available versions of Docker here:
https://dockermsft.azureedge.net/dockercontainer/DockerMsftIndex.json

### CODE REVIEW

**Comment by rofuentes** [comment]
@pjh please take a look at this as well, I will build new container images next week to verify.

**Comment by rofuentes** [comment]
I rebuilt the 2020-06 WfC images with Docker 19.03 and have them in testing/staging now.

**Comment by rofuentes** [comment]
Ran both hello-world and PowerShell test on WS 2019.

```
PS C:\Windows\system32> docker --version
Docker version 19.03.5, build 2ee0c57608
PS C:\Windows\system32> docker run -it hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
...
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

PS C:\Windows\system32> docker run -it mcr.microsoft.com/windows/servercore:ltsc2019 powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.1007
PSEdition                      Desktop
```

**Comment by pjh** [comment]
LGTM too

**Pull request merged**
