### PR TITLE
Move OSConfig agent to own repo

### PR DESCRIPTION
**Pull request by hopkiw**
Moved to https://github.com/GoogleCloudPlatform/osconfig
* Update import paths for `osconfig_tests`
* Update gobuild container image not to invoke build for google-osconfig-agent
* `gofmt -w`

### CODE REVIEW

**Comment by hopkiw** [comment]
Updating gobuild image because it has google-osconfig-agent hardcoded in it. New commit inc with changes to its Dockerfile

**Comment by hopkiw** [comment]
failure was a spurious 502
/gobuild

**Comment by adjackura** [comment]
The gobuild container will need to be updated before passing

**Comment by hopkiw** [comment]
gobuild image was cached.. we don't have caching disabled lol
/gobuild

**Comment by hopkiw** [comment]
shshdhdkgks delete from correct prow cluster, ofc
/gobuild

**Comment by hopkiw** [comment]
interestingly the 'details' link in status is broken, but the status updates from bot in comments have working links.

**Comment by hopkiw** [comment]
ok no the links are uniformly broken. did pruning images do this or is there some other breaking change, i wonder

**Comment by hopkiw** [comment]
ok, fixed the cluster. a key rotation wasn't completed.

/gobuild

**Pull request merged**
